### ISSUE TITLE
List supported browsers on results list

### ISSUE THREAD

**Issue by brpaz** [gabrielpoca/zazu-caniuse#1]
Hello.
It would be nice if the plugin can show the list of supported browsers for a specific feature instead of having to click and open canisue. I would like it to work like the [alfred-canisue-workflow](https://github.com/willfarrell/alfred-caniuse-workflow)

**Comment by gabrielpoca** [comment]
Hi @brpaz , thank you for opening the issue. I added that functionality in https://github.com/gabrielpoca/zazu-caniuse/commit/93f32ac73c08063d444a348e48688b47b0ae793b, please let me know if this is what you have in Alfred.

**Comment by gabrielpoca** [comment]
Closed for lack of activity.
