### ISSUE TITLE
Results not showing

### ISSUE THREAD

**Issue by amykapernick** [gabrielpoca/zazu-caniuse#2]
When I search caniuse for several different things, the results aren't showing
![screen shot 2017-04-04 at 3 20 15 pm](https://cloud.githubusercontent.com/assets/15953185/24645335/4bde6c04-194a-11e7-8975-0e66ba851439.png)

**Comment by gabrielpoca** [comment]
Hi @amykapernick  thank you for reporting. Can you help me debug? I need to see the results of a search `caniuse flex` and `caniuse blur` to pinpoint the issue.

**Comment by amykapernick** [comment]
![screen shot 2017-04-04 at 5 10 26 pm](https://cloud.githubusercontent.com/assets/15953185/24649434/9f2dd020-1959-11e7-9924-51a8bb5e7b28.png)
![screen shot 2017-04-04 at 5 10 11 pm](https://cloud.githubusercontent.com/assets/15953185/24649436/a11ab6c8-1959-11e7-9ff9-b20cf274270b.png)

![screen shot 2017-04-04 at 5 12 17 pm](https://cloud.githubusercontent.com/assets/15953185/24649508/e3da9924-1959-11e7-8894-30e515d2d7c6.png)

**Comment by gabrielpoca** [comment]
hi @amykapernick thank you, I'll work on it and let you know when I have an update 👍

**Comment by gabrielpoca** [comment]
Hi @amykapernick , can you please update the plugins and let me know if it works as you were expecting before?

**Comment by gabrielpoca** [comment]
Closed for lack of activity.
